spring:
  application:
    name: USER-SERVICE

eureka:
  instance:
    hostname: MasamNikhil.mshome.net
    prefer-ip-address: true
    ip-address: 127.0.0.1
    leaseRenewalIntervalInSeconds: 3
  client:
    initialInstanceInfoReplicationIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true


