spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - CustomFilter
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userFallBack
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - CustomFilter
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productFallBack
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review/**
          filters:
            - CustomFilter
            - name: CircuitBreaker
              args:
                name: review-service
                fallbackuri: forward:/reviewFallBack
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowedCredentials: true

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 10000
  ReadTimeout: 10000
  MaxAutoRetries: 2


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  register-with-eureka: true
  fetch-registry: true
  registry-fetch-interval-seconds: 2
  initial-instance-info-replication-interval-seconds: 2

#resiliance
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 3000
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
      product-service:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 3000
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
      review-service:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 3000
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true






