spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - CustomFilter
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userFallBack
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - CustomFilter
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productFallBack
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review/**
          filters:
            - CustomFilter
            - name: CircuitBreaker
              args:
                name: review-service
                fallbackuri: forward:/reviewFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
=======
            timeoutInMilliseconds: 20000

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 5000
  ReadTimeout: 5000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

<<<<<<< HEAD
=======
#Eureka
>>>>>>> 6b6ee8c (sorting added)
eureka:
  instance:
    hostname: MasamNikhil.mshome.net
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

=======
#resiliance
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
      product-service:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
      review-service:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true


